### ISSUE TITLE
Occasional IndexError

### ISSUE THREAD

**Issue by nbowen** [GreshB/Tic-Tac-Toe#2]
Seemingly randomly, the game will exit with:

```
Traceback (most recent call last):
  File "/private/tmp/Tic-Tac-Toe/game.py", line 59, in <module>
    tic_tac_toe()
  File "/private/tmp/Tic-Tac-Toe/game.py", line 53, in tic_tac_toe
    random_move(board, "X")
  File "/private/tmp/Tic-Tac-Toe/game.py", line 16, in random_move
    random.choice(open_spots(board))
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
```

**Comment by nbowen** [comment]
This doesn't seem to be random, on second thought. It looks like that error happens whenever the game has finished in a draw.

**Comment by GreshB** [comment]
Figured it out! Had to do with the while loop running both  an "O" turn and an "X" turn, which could result in "O" creating a draw yet "X" still having to go with no empty spaces left
